// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3J1cpqtGqswQbHOcSdda7oJKaqarl4vo',
    appId: '1:901060192995:web:814f25461634dc0901b3d6',
    messagingSenderId: '901060192995',
    projectId: 'todo-26640',
    authDomain: 'todo-26640.firebaseapp.com',
    storageBucket: 'todo-26640.appspot.com',
    measurementId: 'G-R9MF7192T7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-RM83KL1vAud6kLClSq4QZ-mAT7aScaM',
    appId: '1:901060192995:android:d0fb0151e52e868901b3d6',
    messagingSenderId: '901060192995',
    projectId: 'todo-26640',
    storageBucket: 'todo-26640.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1VURVUln8fA1L772HOajryQsGEDx8aWQ',
    appId: '1:901060192995:ios:1a9cb4312bdcca6e01b3d6',
    messagingSenderId: '901060192995',
    projectId: 'todo-26640',
    storageBucket: 'todo-26640.appspot.com',
    iosClientId: '901060192995-ljhski2uq6jojla8npcfp30spkh4n45t.apps.googleusercontent.com',
    iosBundleId: 'com.example.notez',
  );
}
